apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-cm
data:
  config.yaml: |
    logfile_path: /pv-mount/logs/output.log
    server_port: 5858
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    app: server
    owner: bbozic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
      owner: bbozic
  template:
    metadata:
      labels:
        app: server
        owner: bbozic
    spec:
      containers:
      - name: hello-server
        image: crayonworkshop.azurecr.io/bbozic-http-server-configmap:0.0.1
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: hello-world-secret
              key: password
        ports:
        - containerPort: 5858
          name: server
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
        volumeMounts:
        - mountPath: /data/hello-server/config
          name: hello-server-config
          readOnly: true
      volumes:
      - name: hello-server-config
        configMap:
          name: hello-world-cm
