apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read-delete
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
  - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-delete-pod
subjects:
- kind: ServiceAccount
  name: my-first-service-account
  namespace: bbozic
roleRef:
  kind: Role
  name: pod-read-delete
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
subjects:
- kind: ServiceAccount
  name: my-first-service-account
  namespace: bbozic
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
