apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-server
spec:
  selector:
    matchLabels:
      app: server
      owner: bbozic
  serviceName: hello-server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
        owner: bbozic
    spec:
      containers:
      - name: hello-server
        image: crayonworkshop.azurecr.io/bbozic-http-server-pv:0.0.1
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: hello-world-secret
              key: password
        ports:
        - containerPort: 5858
          name: server
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
        volumeMounts:
        - mountPath: /data/hello-server/config
          name: hello-server-config
          readOnly: true
        - mountPath: /pv-mount/logs
          name: logging
      volumes:
      - name: hello-server-config
        configMap:
          name: hello-world-cm
  volumeClaimTemplates:
  - metadata:
      name: logging
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: managed-csi
      resources:
        requests:
          storage: 1Gi
