apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-server
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: hello-server
        image: crayonworkshop.azurecr.io/bbozic-http-server:0.0.1
        env:
        - name: SERVER_PORT
          value: "5858"
        ports:
        - containerPort: 5858
          name: server
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
