apiVersion: v1
kind: Secret
metadata:
  name: hello-world-secret
data:
  password: MWYyZDFlMmU2N2Rm
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    app: server
    owner: bbozic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
      owner: bbozic
  template:
    metadata:
      labels:
        app: server
        owner: bbozic
    spec:
      containers:
      - name: hello-server
        image: crayonworkshop.azurecr.io/bbozic-http-server-secret:0.0.2
        env:
        - name: SERVER_PORT
          value: "5858"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: hello-world-secret
              key: password
        ports:
        - containerPort: 5858
          name: server
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
# EVERYTHING UNDER HERE OPTIONAL (another way how to use secrets)
        volumeMounts:
        - name: secret-password
          mountPath: "/mysecret/password-secret"
      volumes:
      - name: secret-password
        secret:
          secretName: hello-world-secret
